const KEY='cccs_sttimothy_attendance_v11';
let db=JSON.parse(localStorage.getItem(KEY)||'{"students":[],"attendance":[],"notices":[],"settings":{"school":"Cordova Catholic Cooperative School","late":"07:30"}}');
const save=()=>localStorage.setItem(KEY,JSON.stringify(db));
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const localDate=()=>{let d=new Date(),y=d.getFullYear(),m=String(d.getMonth()+1).padStart(2,'0'),day=String(d.getDate()).padStart(2,'0');return `${y}-${m}-${day}`};
const fmt=d=>new Date(d).toLocaleString();
function code(){let y=new Date().getFullYear(),n=db.students.length+1,c;do{c=`CCCS-${y}-${String(n++).padStart(5,'0')}`}while(db.students.some(s=>s.code===c));return c}
function statusFor(s){let a=db.attendance.filter(x=>x.studentId===s.id&&x.date===localDate()&&x.type==='IN');if(!a.length)return 'Not Checked In';return a.some(x=>x.late)?'Late':'Present'}
function render(){let ta=db.attendance.filter(a=>a.date===localDate()),ins=new Set();ta.forEach(a=>a.type==='IN'?ins.add(a.studentId):ins.delete(a.studentId));sTotal.textContent=db.students.length;sPresent.textContent=new Set(ta.filter(a=>a.type==='IN').map(a=>a.studentId)).size;sLate.textContent=new Set(ta.filter(a=>a.type==='IN'&&a.late).map(a=>a.studentId)).size;sInside.textContent=ins.size;
recent.innerHTML=ta.slice(-8).reverse().map(a=>{let s=db.students.find(x=>x.id===a.studentId);return `<div class='notice'><b>${esc(s?.name||'Unknown')}</b> <span class='pill ${a.type==='OUT'?'out':''}'>${a.type}</span><br><small>${fmt(a.at)} ${a.late?'• LATE':''}</small></div>`}).join('')||'<p class=muted>No attendance yet.</p>';
notices.innerHTML=db.notices.slice(-6).reverse().map(n=>`<div class='notice'><span class='ok'>✓ SMS simulated</span><br>${esc(n.message)}<br><small>${fmt(n.at)}</small></div>`).join('')||'<p class=muted>No notifications yet.</p>';renderStudents();renderAttendance();renderBoard();renderReports()}
function renderStudents(){let q=(studentSearch?.value||'').toLowerCase(),arr=db.students.filter(s=>[s.name,s.lrn,s.code].some(v=>String(v).toLowerCase().includes(q)));studentList.innerHTML=arr.length?`<div class='studentCards'>${arr.map(s=>`<article class='studentCard'><div><span class='mini'>${esc(s.code)}</span><h3>${esc(s.name)}</h3><p>LRN: ${esc(s.lrn)}<br>Grade 11 – St. Timothy<br>Guardian: ${esc(s.guardian)}<br>Mobile: ${esc(s.mobile)}</p></div><div class='qrMini' id='qr-${esc(s.id)}'></div><button data-showqr='${esc(s.id)}'>Show QR</button></article>`).join('')}</div>`:'<p class=muted>No St. Timothy students enrolled.</p>';document.querySelectorAll('[data-showqr]').forEach(b=>b.onclick=()=>showQR(b.dataset.showqr))}
function showQR(id){let s=db.students.find(x=>x.id===id);if(!s)return;let w=window.open('','_blank','width=430,height=620');w.document.write(`<title>${esc(s.name)} QR</title><style>body{font-family:Arial;text-align:center;padding:30px}#q{display:flex;justify-content:center;margin:25px}.code{font-size:22px;font-weight:bold}.muted{color:#555}</style><h2>Grade 11 – St. Timothy</h2><h1>${esc(s.name)}</h1><div id='q'></div><div class='code'>${esc(s.code)}</div><p class='muted'>Attendance QR • Do not share publicly</p><script src='https://cdnjs.cloudflare.com/ajax/libs/qrcodejs/1.0.0/qrcode.min.js'><\/script><script>window.onload=()=>new QRCode(document.getElementById('q'),{text:${JSON.stringify(s.code)},width:220,height:220})<\/script>`);w.document.close()}
function renderAttendance(){let arr=db.attendance.filter(a=>a.date===localDate()).slice().reverse();attendanceList.innerHTML=arr.length?`<table><tr><th>Time</th><th>Student</th><th>Event</th><th>Status</th></tr>${arr.map(a=>{let s=db.students.find(x=>x.id===a.studentId);return `<tr><td>${new Date(a.at).toLocaleTimeString()}</td><td>${esc(s?.name)}</td><td>${a.type}</td><td>${a.late?'Late':'Recorded'}</td></tr>`}).join('')}</table>`:'<p class=muted>No attendance today.</p>'}
function renderBoard(){sectionBoard.innerHTML=db.students.length?`<div class='boardGrid'>${db.students.slice().sort((a,b)=>a.name.localeCompare(b.name)).map(s=>{let st=statusFor(s),cls=st==='Present'?'present':st==='Late'?'late':'unchecked';return `<div class='boardStudent ${cls}'><b>${esc(s.name)}</b><span>${st==='Present'?'🟢':st==='Late'?'🟡':'⚪'} ${st}</span></div>`}).join('')}</div>`:'<p class=muted>No students enrolled.</p>'}
function renderReports(){reportList.innerHTML=db.attendance.length?`<table><tr><th>Date/Time</th><th>Student</th><th>Event</th><th>Late</th></tr>${db.attendance.slice().reverse().map(a=>{let s=db.students.find(x=>x.id===a.studentId);return `<tr><td>${fmt(a.at)}</td><td>${esc(s?.name)}</td><td>${a.type}</td><td>${a.late?'Yes':'No'}</td></tr>`}).join('')}</table>`:'<p class=muted>No records.</p>'}
function recordCode(c){let type=scanType.value,s=db.students.find(x=>x.code.toLowerCase()===String(c).trim().toLowerCase());if(!s){scanResult.innerHTML='<p class=bad>Student code not found.</p>';return false}let now=new Date(),hm=now.toTimeString().slice(0,5),late=type==='IN'&&hm>(db.settings.late||'07:30'),last=db.attendance.filter(a=>a.studentId===s.id&&a.date===localDate()).at(-1);if(last?.type===type){scanResult.innerHTML=`<p class=bad>${esc(s.name)} already has a ${type} record as the latest event today.</p>`;return false}let a={id:(crypto.randomUUID?.()||Date.now().toString()),studentId:s.id,type,at:now.toISOString(),date:localDate(),late};db.attendance.push(a);let verb=type==='IN'?'entered the school':'left the school',msg=`${db.settings.school||'School'} Attendance: ${s.name} ${verb} at ${now.toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})} on ${now.toLocaleDateString()}.`;db.notices.push({at:now.toISOString(),studentId:s.id,mobile:s.mobile,message:msg,status:'simulated'});save();scanResult.innerHTML=`<div class='result'><h3 class=ok>${type==='IN'?'✓ Time In':'✓ Time Out'} recorded</h3><p><b>${esc(s.name)}</b>${late?' • LATE':''}</p><p>${esc(msg)}</p><small>Parent SMS simulation → ${esc(s.mobile)}</small></div>`;scanCode.value='';render();return true}
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>{document.querySelectorAll('nav button,.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelector('#'+b.dataset.tab).classList.add('active');if(b.dataset.tab!=='scanner')stopCamera()});
enrollForm.onsubmit=e=>{e.preventDefault();let f=Object.fromEntries(new FormData(e.target));if(db.students.some(s=>s.lrn===f.lrn))return alert('This LRN is already enrolled.');let s={...f,grade:'Grade 11',section:'St. Timothy',id:crypto.randomUUID?.()||Date.now().toString(),code:code(),createdAt:new Date().toISOString()};db.students.push(s);save();enrollResult.innerHTML=`<div class='result'><h3>Enrollment Successful</h3><p>${esc(s.name)} is enrolled in <b>Grade 11 – St. Timothy</b>.</p><div class='code'>${esc(s.code)}</div><div id='newQR' class='qrBox'></div><p><button id='openStudentQR'>Open / Print Student QR</button></p><small>This QR contains only the generated attendance code, not the student's LRN or personal information.</small></div>`;if(window.QRCode)new QRCode(document.getElementById('newQR'),{text:s.code,width:180,height:180});document.querySelector('#openStudentQR').onclick=()=>showQR(s.id);e.target.reset();render()};
studentSearch.oninput=renderStudents;scanBtn.onclick=()=>recordCode(scanCode.value);refreshBoard.onclick=renderBoard;
exportBtn.onclick=()=>{let rows=[['Date/Time','LRN','Student Code','Name','Grade','Section','Event','Late']];db.attendance.forEach(a=>{let s=db.students.find(x=>x.id===a.studentId)||{};rows.push([a.at,s.lrn,s.code,s.name,'Grade 11','St. Timothy',a.type,a.late?'Yes':'No'])});let csv=rows.map(r=>r.map(v=>'"'+String(v??'').replaceAll('"','""')+'"').join(',')).join('\n'),url=URL.createObjectURL(new Blob([csv],{type:'text/csv'})),x=document.createElement('a');x.href=url;x.download='St_Timothy_Attendance_Report.csv';x.click();URL.revokeObjectURL(url)};
schoolName.value=db.settings.school||'';lateTime.value=db.settings.late||'07:30';saveSettings.onclick=()=>{db.settings.school=schoolName.value;db.settings.late=lateTime.value;save();alert('Settings saved.')};
let stream=null,scanTimer=null;async function startCamera(){cameraNote.textContent='Opening camera…';if(!('BarcodeDetector'in window)){cameraNote.innerHTML='<span class="bad">This browser does not provide built-in QR detection. Try current Chrome/Android or use manual code entry.</span>';return}try{let detector=new BarcodeDetector({formats:['qr_code']});stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'}},audio:false});camera.srcObject=stream;await camera.play();cameraWrap.hidden=false;startCamera.hidden=true;stopCamera.hidden=false;cameraNote.textContent='Point the camera at a St. Timothy student QR code.';scanTimer=setInterval(async()=>{try{let codes=await detector.detect(camera);if(codes.length){let raw=codes[0].rawValue;if(recordCode(raw)){navigator.vibrate?.(120);await stopCamera();setTimeout(()=>startCamera.click(),700)}}}catch(e){}},450)}catch(e){cameraNote.innerHTML=`<span class='bad'>Camera could not start: ${esc(e.message)}. Check browser camera permission.</span>`}}
async function stopCamera(){if(scanTimer){clearInterval(scanTimer);scanTimer=null}if(stream){stream.getTracks().forEach(t=>t.stop());stream=null}cameraWrap.hidden=true;startCamera.hidden=false;stopCamera.hidden=true}
startCamera.onclick=startCamera;stopCamera.onclick=stopCamera;
let deferred;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferred=e;installBtn.hidden=false});installBtn.onclick=async()=>{if(deferred){deferred.prompt();await deferred.userChoice;deferred=null;installBtn.hidden=true}};if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js?v=1.1');render();
